src/Entity/Blockchain.php
<?php

namespace App\Entity;

use App\Repository\BlockchainRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=BlockchainRepository::class)
 *
 * @ApiResource(
 *     collectionOperations={
 *          "get"={"get"={"method"="POST"}},
 *     },
 *     itemOperations={
 *          "get"
 *     }
 * )
 */
class Blockchain
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank()
     * @Assert\Length(
     *     min=2,
     *     max=50
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min=10,
     *     max=100
     * )
     */
    private $cle_api;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Wallet", mappedBy="blockchain")
     */
    private $wallets;

    public function __construct()
    {
        $this->wallets = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCleApi(): ?string
    {
        return $this->cle_api;
    }

    public function setCleApi(string $cle_api): self
    {
        $this->cle_api = $cle_api;

        return $this;
    }

    public function postUpdate(){

    }

    /**
     * @return Collection|Wallet[]
     */
    public function getWallets(): Collection
    {
        return $this->wallets;
    }

    public function addWallet(Wallet $wallet): self
    {
        if (!$this->wallets->contains($wallet)) {
            $this->wallets[] = $wallet;
            $wallet->setBlockchain($this);
        }

        return $this;
    }

    public function removeWallet(Wallet $wallet): self
    {
        if ($this->wallets->contains($wallet)) {
            $this->wallets->removeElement($wallet);
            // set the owning side to null (unless already changed)
            if ($wallet->getBlockchain() === $this) {
                $wallet->setBlockchain(null);
            }
        }

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Form/BlockchainType.php
<?php

namespace App\Form;

use App\Entity\Blockchain;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BlockchainType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('cle_api')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blockchain::class,
        ]);
    }
}

src/Controller/BlockchainController.php
<?php

namespace App\Controller;

use App\Entity\Blockchain;
use App\Form\BlockchainType;
use App\Repository\BlockchainRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/blockchain")
 */
class BlockchainController extends AbstractController
{
    /**
     * @Route("/", name="blockchain_index", methods={"GET"})
     */
    public function index(BlockchainRepository $blockchainRepository): Response
    {
        return $this->render('blockchain/index.html.twig', [
            'blockchains' => $blockchainRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="blockchain_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $blockchain = new Blockchain();
        $form = $this->createForm(BlockchainType::class, $blockchain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($blockchain);
            $entityManager->flush();

            return $this->redirectToRoute('blockchain_index');
        }

        return $this->render('blockchain/new.html.twig', [
            'blockchain' => $blockchain,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="blockchain_show", methods={"GET"})
     */
    public function show(Blockchain $blockchain): Response
    {
        return $this->render('blockchain/show.html.twig', [
            'blockchain' => $blockchain,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="blockchain_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Blockchain $blockchain): Response
    {
        $form = $this->createForm(BlockchainType::class, $blockchain);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('blockchain_index');
        }

        return $this->render('blockchain/edit.html.twig', [
            'blockchain' => $blockchain,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="blockchain_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Blockchain $blockchain): Response
    {
        if ($this->isCsrfTokenValid('delete'.$blockchain->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($blockchain);
            $entityManager->flush();
        }

        return $this->redirectToRoute('blockchain_index');
    }
}

templates/blockchain/_delete_form.html.twig
<form method="post" action="{{ path('blockchain_delete', {'id': blockchain.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ blockchain.id) }}">
    <button class="btn">Delete</button>
</form>

templates/blockchain/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/blockchain/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Blockchain{% endblock %}

{% block body %}
    <h1>Edit Blockchain</h1>

    {{ include('blockchain/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('blockchain_index') }}">back to list</a>

    {{ include('blockchain/_delete_form.html.twig') }}
{% endblock %}

templates/blockchain/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blockchain index{% endblock %}

{% block body %}
    <h1>Blockchain index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Cle_api</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for blockchain in blockchains %}
            <tr>
                <td>{{ blockchain.id }}</td>
                <td>{{ blockchain.name }}</td>
                <td>{{ blockchain.cleApi }}</td>
                <td>
                    <a href="{{ path('blockchain_show', {'id': blockchain.id}) }}">show</a>
                    <a href="{{ path('blockchain_edit', {'id': blockchain.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('blockchain_new') }}">Create new</a>
{% endblock %}

templates/blockchain/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Blockchain{% endblock %}

{% block body %}
    <h1>Create new Blockchain</h1>

    {{ include('blockchain/_form.html.twig') }}

    <a href="{{ path('blockchain_index') }}">back to list</a>
{% endblock %}

templates/blockchain/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blockchain{% endblock %}

{% block body %}
    <h1>Blockchain</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ blockchain.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ blockchain.name }}</td>
            </tr>
            <tr>
                <th>Cle_api</th>
                <td>{{ blockchain.cleApi }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('blockchain_index') }}">back to list</a>

    <a href="{{ path('blockchain_edit', {'id': blockchain.id}) }}">edit</a>

    {{ include('blockchain/_delete_form.html.twig') }}
{% endblock %}